// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnMeIR4XOIWOXa2-XpJDORRosdPA9i42Q',
    appId: '1:989241975669:web:4953f941e9e51c778fe93c',
    messagingSenderId: '989241975669',
    projectId: 'basic-auth-example',
    authDomain: 'basic-auth-example.firebaseapp.com',
    storageBucket: 'basic-auth-example.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJa6HSukm8Hb9_VTrN91tw08Z5-onizd0',
    appId: '1:989241975669:android:c9d4094da58214b78fe93c',
    messagingSenderId: '989241975669',
    projectId: 'basic-auth-example',
    storageBucket: 'basic-auth-example.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH4w9LRHbLRmCiizQDFLbOgO-jsDzCZm8',
    appId: '1:989241975669:ios:5b9283b323f69f628fe93c',
    messagingSenderId: '989241975669',
    projectId: 'basic-auth-example',
    storageBucket: 'basic-auth-example.appspot.com',
    iosClientId: '989241975669-81hdjknf4oq0hpu01vvt7vcq06pp3939.apps.googleusercontent.com',
    iosBundleId: 'co.enspyr.basicAuthExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH4w9LRHbLRmCiizQDFLbOgO-jsDzCZm8',
    appId: '1:989241975669:ios:5b9283b323f69f628fe93c',
    messagingSenderId: '989241975669',
    projectId: 'basic-auth-example',
    storageBucket: 'basic-auth-example.appspot.com',
    iosClientId: '989241975669-81hdjknf4oq0hpu01vvt7vcq06pp3939.apps.googleusercontent.com',
    iosBundleId: 'co.enspyr.basicAuthExample',
  );
}
